# Generated by Django 5.0.3 on 2026-06-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_servicerequest_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط العرض'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='خط الطول'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='estimated_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='السعر التقديري (د.ع)'),
        ),
    ]
