# Generated by Django 5.0.3 on 2026-06-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_servicerequest_lat_servicerequest_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='related_profession',
            field=models.CharField(blank=True, choices=[('lawyer', 'محامٍ'), ('agent', 'معقب معاملات'), ('accountant', 'محاسب'), ('other', 'خدمات أخرى')], max_length=20, null=True, verbose_name='المهنة المرتبطة'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
    ]
