# Generated by Django 6.0.4 on 2026-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_category_related_profession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='related_profession',
            field=models.CharField(blank=True, choices=[('lawyer', 'محامٍ'), ('electrician', 'كهربائي'), ('plumber', 'سباك'), ('mason', 'بناء'), ('painter', 'دهان'), ('carpenter', 'نجار'), ('hvac', 'فني تبريد وتكييف'), ('tile_mason', 'سيراميك'), ('developer', 'مبرمج'), ('engineer', 'مهندس'), ('security_tech', 'فني أنظمة أمنية'), ('clearance_agent', 'معقب معاملات'), ('accountant', 'محاسب'), ('other', 'خدمات أخرى')], max_length=20, null=True, verbose_name='المهنة المرتبطة'),
        ),
    ]
