# Generated by Django 5.2.13 on 2026-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_category_related_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='خط الطول'),
        ),
    ]
