# Generated by Django 5.2.13 on 2026-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_servicerequest_lat_alter_servicerequest_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط الطول'),
        ),
    ]
