# Generated by Django 5.2.13 on 2026-07-13 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_servicerequest_lat_alter_servicerequest_lon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('to_agent', 'تقييم للمهني'), ('to_customer', 'تقييم للزبون')], default='to_agent', max_length=20),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_about_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.servicerequest'),
        ),
        migrations.RemoveField(
            model_name='review',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='review',
            name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('request', 'reviewer', 'review_type')},
        ),
    ]
