# Generated by Django 6.0.5 on 2026-05-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=120, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='profession',
            field=models.CharField(choices=[('lawyer', 'محامٍ'), ('agent', 'معقب معاملات'), ('accountant', 'محاسب'), ('other', 'خدمات أخرى')], default='other', max_length=20, verbose_name='نوع المهنة'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='service_max_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='أعلى سعر خدمة'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='service_min_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='أقل سعر خدمة'),
        ),
    ]
