# Generated by Django 5.2.13 on 2026-05-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_agentprofile_city_agentprofile_profession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet_balance',
            field=models.IntegerField(default=0, verbose_name='رصيد المحفظة'),
        ),
    ]
