# Generated by Django 5.0.3 on 2026-06-09 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_agentprofile_lat_agentprofile_lon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={},
        ),
    ]
