# Generated by Django 5.0.3 on 2026-06-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_agentprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': 'ملف مندوب', 'verbose_name_plural': 'ملفات المندوبين'},
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='custom_profession',
            field=models.CharField(blank=True, max_length=100, verbose_name='مهنة أخرى'),
        ),
    ]
