# Generated by Django 6.0.4 on 2026-06-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_agentprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='profession',
            field=models.CharField(choices=[('lawyer', 'محامٍ'), ('electrician', 'كهربائي'), ('plumber', 'سباك'), ('mason', 'بناء'), ('painter', 'دهان'), ('carpenter', 'نجار'), ('hvac', 'فني تبريد وتكييف'), ('tile_mason', 'سيراميك'), ('developer', 'مبرمج'), ('engineer', 'مهندس'), ('security_tech', 'فني أنظمة أمنية'), ('clearance_agent', 'معقب معاملات'), ('accountant', 'محاسب'), ('other', 'خدمات أخرى')], default='other', max_length=20, verbose_name='نوع المهنة'),
        ),
    ]
