# Generated by Django 6.0.4 on 2026-06-11 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_agentprofile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('agent_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_images', to='authentication.agentprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
