# Generated by Django 6.0.4 on 2026-06-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_user_reset_code_user_reset_code_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='needs_phone_completion',
            field=models.BooleanField(default=False, verbose_name='بحاجة لتكملة رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
    ]
