# Generated by Django 6.0.4 on 2026-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_user_needs_phone_completion_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='temp_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='رقم مؤقت للتحقق'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رمز التحقق'),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_code_expiry',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انتهاء صلاحية الرمز'),
        ),
    ]
