# Generated by Django 5.2.13 on 2026-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_portfolioimage_options_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توكن الإشعارات'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True, verbose_name='خط الطول'),
        ),
    ]
