# Generated by Django 5.2.13 on 2026-07-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_user_fcm_token_alter_agentprofile_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='full_name_at_verification',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الاسم الكامل عند التوثيق'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الواتساب'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='id_card_back',
            field=models.ImageField(blank=True, null=True, upload_to='identity/', verbose_name='ظهر البطاقة الموحدة'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='id_card_front',
            field=models.ImageField(blank=True, null=True, upload_to='identity/', verbose_name='وجه البطاقة الموحدة'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط العرض'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='خط الطول'),
        ),
    ]
