# Generated by Django 5.2.13 on 2026-07-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_agentprofile_full_name_at_verification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blacklisted_reason',
            field=models.TextField(blank=True, verbose_name='سبب الحظر'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_rating',
            field=models.FloatField(default=0.0, verbose_name='تقييم الزبون'),
        ),
        migrations.AddField(
            model_name='user',
            name='customer_total_reviews',
            field=models.IntegerField(default=0, verbose_name='إجمالي تقييمات الزبون'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_blacklisted',
            field=models.BooleanField(default=False, verbose_name='محظور من النظام'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_customer_verified',
            field=models.BooleanField(default=False, verbose_name='زبون موثق'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='متاح حالياً'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر ظهور'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'زبون'), ('agent', 'مهني'), ('admin', 'مدير النظام')], default='customer', max_length=15, verbose_name='الدور النشط الحالي'),
        ),
    ]
