# Generated by Django 5.2.13 on 2026-07-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_user_blacklisted_reason_user_customer_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='needs_phone_completion',
        ),
        migrations.AddField(
            model_name='user',
            name='is_profile_complete',
            field=models.BooleanField(default=False, verbose_name='الملف الشخصي مكتمل'),
        ),
    ]
